# comando para inserir a interfaceRedeTraefik.yml ao arquivo docker-compose.yml e criar o arquivo compose_final.yml
yq eval-all 'select(fileIndex == 0) * select(fileIndex == 1)' interfaceRede.yml docker-compose.yml > compose.yml

# Linhas de interface de rede a serem adicionadas ao arquivo compose do archivematica
services:
  mysql:
    networks:
      - default

  elasticsearch:
    networks:
      - default
      
  gearmand:
    networks:
      - default

  clamavd:
    networks:
      - default

  archivematica-mcp-server:
    networks:
      - default

  archivematica-mcp-client:
    networks:
      - default
      - traefik
      - integracao

  archivematica-dashboard:
    networks:
      - default
      - traefik
      - integracao

  archivematica-storage-service:
    networks:
      - default
      - traefik

# definição dos networks e volumes
networks:
  default:
  traefik:
    external:
      name: traefik
  integracao:
    external:
      name: integracao
