version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik"
      traefik.http.routers.portainer.rule: "Host(`portainer.tre-ac.jus.br`)"
      traefik.http.routers.portainer.entrypoints: "web"          # HTTP (80)
      # NADA de tls.* aqui
      traefik.http.routers.portainer.service: "portainer"
      traefik.http.services.portainer.loadbalancer.server.port: "9000"
      # (opcional) middlewares só se você quiser; evite middleware de redirecionamento p/ HTTPS
    networks:
      - traefik
    ports:
      - "9000:9000"
    restart: unless-stopped
networks:
  traefik:
    external: true

volumes:
  portainer_data: